CREATE TABLE ALLOWEDUSER
  (
     ID          BIGINT NOT NULL AUTO_INCREMENT,
     USERALIAS   VARCHAR(64) NOT NULL UNIQUE,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX ALLOWEDUSER_INDEX ON ALLOWEDUSER(ID);