INSERT INTO PROJECT VALUES(5, STRINGDECODE('Die Kompetenzmatrix hilft bei der Ermittlung der fachlichen Kompetenz eines Bewerbers. Ein Beispiel f\u00fcr Softwareentwickler ist unter http://cdn.pearltrees.com/s/pic/sq/programmer-competency-matrix-710434) zu finden.'), 'starwit', 'LJ_CompetencyMatrix8814891669789836253', 'CompetencyMatrix', 1);
INSERT INTO PROJECT VALUES(6, STRINGDECODE('Dieses Projekt dient zur Sammlung neuer Anwendungsideen. Nach einer ersten kurzen Beschreibung k\u00f6nnen diese immer mehr ausdifferenziert und bewertet werden.'), 'starwit', 'LJ_InnovationLab8683024454803458207', 'InnovationLab', 1);

INSERT INTO DOMAIN VALUES(11, STRINGDECODE('Alle eingetragenen Fragen bilden den Fragenkatalog f\u00fcr das Kompetenzprofil'), 'Question', 5);
INSERT INTO DOMAIN VALUES(12, 'Dem Nutzer zugeordnetes Kompetenzprofil', 'CompetenceProfile', 5);
INSERT INTO DOMAIN VALUES(13, 'Das Level des Nutzers in dem jeweiligen Kompetenzbereich', 'CompetenceEvaluation', 5);
INSERT INTO DOMAIN VALUES(14, 'Die Antworten des Nutzers auf die Fragen.', 'Answer', 5);
INSERT INTO DOMAIN VALUES(15, STRINGDECODE('Die Idee f\u00fcr die neue Anwendung.'), 'Idea', 6);
INSERT INTO DOMAIN VALUES(16, STRINGDECODE('Name der Kompetenz / F\u00e4higkeit, die der zu Bewertende mitbringen soll.'), 'Competence', 5);
INSERT INTO DOMAIN VALUES(17, STRINGDECODE('Kompetenzmatrix f\u00fcr das jeweilige Berufsbild'), 'CompetenceMatrix', 5);
INSERT INTO DOMAIN VALUES(18, STRINGDECODE('Kandidat, der ein Kompetenzprofil ablegen m\u00f6chte oder Bewerter f\u00fcr Kompetenzprofile.'), 'User', 5);
INSERT INTO DOMAIN VALUES(19, 'adshfsd fsfh sfh', 'User', 6);

INSERT INTO ATTRIBUTE VALUES(20, 'String', NULL, 150, 1, 'competence', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(21, 'Integer', NULL, 3, 0, 'level', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(22, 'String', NULL, 260, 1, 'description', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(24, 'String', 'zu Bewertender Nutzer', NULL, NULL, 'user', TRUE, '');
INSERT INTO ATTRIBUTE VALUES(25, 'String', 'Bewerter', NULL, NULL, 'evaluator', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(26, 'String', STRINGDECODE('Liste der bewerteten F\u00e4higkeiten'), NULL, NULL, 'competenceEvaluations', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(27, 'String', 'Kompetenzbereich', NULL, NULL, 'competence', TRUE, '/^[a-zA-Z0-9]*$/');
INSERT INTO ATTRIBUTE VALUES(28, 'String', 'Liste der Antworten zu dem Kompetenzbereich', NULL, NULL, 'answers', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(29, 'String', 'Wissensstand', NULL, NULL, 'level', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(30, 'String', NULL, 260, 1, 'question', FALSE, '');
INSERT INTO ATTRIBUTE VALUES(32, 'String', NULL, 260, 1, 'answer', FALSE, NULL);
INSERT INTO ATTRIBUTE VALUES(33, 'String', NULL, NULL, NULL, 'passed', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(34, 'String', 'Titel', 150, 1, 'headline', FALSE, '');
INSERT INTO ATTRIBUTE VALUES(35, 'String', 'Beschreibung der Anwendungsidee', 260, 1, 'description', FALSE, '');
INSERT INTO ATTRIBUTE VALUES(36, 'String', 'sonstige Anmerkungen (z.B. URLs, Beispiele)', 260, 1, 'notes', TRUE, '');
INSERT INTO ATTRIBUTE VALUES(37, 'String', STRINGDECODE('Name der F\u00e4higkeit'), 150, 1, 'title', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(38, 'String', STRINGDECODE('F\u00e4higkeitsbeschreibung'), 250, NULL, 'description', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(39, 'String', 'Bezeichnung des Berufsbildes', 150, 1, 'title', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(40, 'String', STRINGDECODE('Beschreibung f\u00fcr das Berufsbild'), 150, 1, 'description', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(41, 'String', 'Liste der Kompetenzen', NULL, NULL, 'competences', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(42, 'String', NULL, 150, 1, 'title', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(43, 'String', STRINGDECODE('das zugeh\u00f6rige Kompetenzprofil'), NULL, NULL, 'competenceProfile', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(44, 'String', 'Vorname', 150, 1, 'firstname', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(45, 'String', 'Nachname', 150, 1, 'lastname', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(46, 'String', 'Name, mit der sich der Kandidat / Bewerter anmeldet', 150, 1, 'login', TRUE, '^[a-zA-Z0-9]*$');
INSERT INTO ATTRIBUTE VALUES(47, 'Enum', 'Rolle (Kandidat, Admin oder Bewerter)', NULL, NULL, 'role', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(48, 'Integer', 'Bewertung', 5, 0, 'rating', FALSE, '^[0-5]*$');
INSERT INTO ATTRIBUTE VALUES(49, 'Date', 'Erstellungsdatum', NULL, NULL, 'created', FALSE, NULL);
INSERT INTO ATTRIBUTE VALUES(50, 'Timestamp', STRINGDECODE('Test f\u00fcr einen Zeitstempel'), NULL, NULL, 'timecreated', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(51, 'String', NULL, NULL, NULL, 'lastname', TRUE, NULL);
INSERT INTO ATTRIBUTE VALUES(52, 'String', NULL, NULL, NULL, 'firstname', TRUE, NULL);

INSERT INTO DOMAIN_ATTRIBUTE VALUES(17, 39);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(17, 40);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(17, 41);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(16, 37);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(16, 38);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(12, 24);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(12, 25);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(12, 26);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(13, 27);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(13, 28);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(13, 29);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(13, 43);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 34);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 35);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 36);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 48);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 49);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(15, 50);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(14, 30);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(14, 32);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(14, 33);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(19, 51);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(19, 52);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(18, 44);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(18, 45);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(18, 46);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(18, 47);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(11, 20);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(11, 21);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(11, 22);
INSERT INTO DOMAIN_ATTRIBUTE VALUES(11, 42);