INSERT INTO APPTEMPLATE(BRANCH,CREDENTIALS_REQUIRED,DESCRIPTION,LOCATION,PREFIX,TITLE) VALUES('main',0,'LireJarp@Spring - github master template','https://github.com/starwit/project-templates.git','xyz','lirejarp');
-- all templates for category ENTITY
INSERT INTO CATEGORY (NAME) VALUES ('ENTITY');
INSERT INTO CATEGORY (NAME) VALUES ('SERVICE');
INSERT INTO CATEGORY (NAME) VALUES ('REST');
INSERT INTO CATEGORY (NAME) VALUES ('FRONTEND');


INSERT INTO TEMPLATEFILE(CREATE_DOMAIN_DIR,FILE_NAME_SUFFIX,LOWER_CASE,TARGET_PATH,TEMPLATE_PATH,TEMPLATE_TYPE,FIRST_UPPER,CATEGORY_ID,APPTEMPLATE_ID) VALUES
    (0,'Repository.java',0,'${apphome}/${app.targetPath}/${app.title}/persistence/src/main/java/de/${app.packagePrefix?lower_case}/persistence/repository/','${apphome}/${app.targetPath}/generator-templates/persistence/EntityRepository.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'RepositoryTest.java',0,'${apphome}/${app.targetPath}/${app.title}/persistence/src/test/java/de/${app.packagePrefix?lower_case}/persistence/repository/','${apphome}/${app.targetPath}/generator-templates/persistence/EntityRepositoryTest.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'.java',0,'${apphome}/${app.targetPath}/${app.title}/persistence/src/main/java/de/${app.packagePrefix?lower_case}/persistence/entity/','${apphome}/${app.targetPath}/generator-templates/persistence/Entity.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'application.properties',1,'${apphome}/${app.targetPath}/${app.title}/application/src/main/resources/','${apphome}/${app.targetPath}/generator-templates/application/properties.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'V1_0__init.sql',0,'${apphome}/${app.targetPath}/${app.title}/persistence/src/main/resources/db/migration/','${apphome}/${app.targetPath}/generator-templates/flyway/V1_0__init.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'version_up.sh',0,'${apphome}/${app.targetPath}/${app.title}/buildScripts/','${apphome}/${app.targetPath}/generator-templates/buildScripts/version_up.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'Makefile',0,'${apphome}/${app.targetPath}/${app.title}/','${apphome}/${app.targetPath}/generator-templates/buildScripts/Makefile.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'ENTITY'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),

    (0,'Service.java',0,'${apphome}/${app.targetPath}/${app.title}/service/src/main/java/de/${app.packagePrefix?lower_case}/service/impl/','${apphome}/${app.targetPath}/generator-templates/service/Service.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'SERVICE'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'ServiceTest.java',0,'${apphome}/${app.targetPath}/${app.title}/service/src/test/java/de/${app.packagePrefix?lower_case}/service/','${apphome}/${app.targetPath}/generator-templates/service/ServiceTest.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'SERVICE'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),

    (0,'Controller.java',0,'${apphome}/${app.targetPath}/${app.title}/rest/src/main/java/de/${app.packagePrefix?lower_case}/rest/controller/','${apphome}/${app.targetPath}/generator-templates/rest/Controller.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'REST'),1),
    (0,'ControllerTest.java',0,'${apphome}/${app.targetPath}/${app.title}/rest/src/test/java/de/${app.packagePrefix?lower_case}/rest/controller/','${apphome}/${app.targetPath}/generator-templates/rest/ControllerTest.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'REST'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),

    (0,'Main.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/pages/${domain.name?lower_case}/','${apphome}/${app.targetPath}/generator-templates/webclient/EntityMainComponent.ftl','DOMAIN',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'All.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/pages/${domain.name?lower_case}/all/','${apphome}/${app.targetPath}/generator-templates/webclient/EntityAllComponent.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'Single.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/pages/${domain.name?lower_case}/single/','${apphome}/${app.targetPath}/generator-templates/webclient/EntitySingleComponent.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/model/','${apphome}/${app.targetPath}/generator-templates/webclient/Model.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'Rest.js',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/services/','${apphome}/${app.targetPath}/generator-templates/webclient/EntityRest.ftl','DOMAIN',1,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'App.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/','${apphome}/${app.targetPath}/generator-templates/webclient/App.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'index.html',1,'${apphome}/${app.targetPath}/${app.title}/webclient/app/public/','${apphome}/${app.targetPath}/generator-templates/webclient/index.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'AppNavigationMenu.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/contentProvider/','${apphome}/${app.targetPath}/generator-templates/webclient/NavbarContentProvider.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'MainContentRouter.jsx',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/app/pages/','${apphome}/${app.targetPath}/generator-templates/webclient/MainContentRouter.ftl','GLOBAL',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'translations-de-DE.json',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/localization','${apphome}/${app.targetPath}/generator-templates/webclient/translation.ftl','ADDITIONAL_CONTENT',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp')),
    (0,'translations-en-US.json',0,'${apphome}/${app.targetPath}/${app.title}/webclient/app/src/localization','${apphome}/${app.targetPath}/generator-templates/webclient/translation.ftl','ADDITIONAL_CONTENT',0,(SELECT ID FROM CATEGORY WHERE NAME LIKE 'FRONTEND'),(SELECT ID FROM APPTEMPLATE WHERE TITLE LIKE 'lirejarp'));
