
DROP TABLE ALLOWEDUSER;

ALTER TABLE APP ADD COLUMN GROUPS VARCHAR(1000) NOT NULL DEFAULT "projectbuilder-default";
ALTER TABLE APPTEMPLATE ADD COLUMN GROUPS VARCHAR(1000) NOT NULL DEFAULT "projectbuilder-default";