
CREATE TABLE DIAGRAM_POSITION
  (
     ID           BIGINT NOT NULL AUTO_INCREMENT,
     POSITION_X   BIGINT NOT NULL DEFAULT 0,
     POSITION_Y   BIGINT NOT NULL DEFAULT 0,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX POSITION_INDEX ON DIAGRAM_POSITION(ID);
ALTER TABLE DOMAIN ADD COLUMN POSITION_ID BIGINT DEFAULT NULL; 
ALTER TABLE DOMAIN
  ADD CONSTRAINT FK_DOMAIN_POS FOREIGN KEY (POSITION_ID) REFERENCES
  DIAGRAM_POSITION(ID);
CREATE INDEX DOMAIN_POSTION_INDEX ON DOMAIN(POSITION_ID);