CREATE TABLE ATTRIBUTE
  (
     ID          BIGINT NOT NULL AUTO_INCREMENT,
     TYPE        VARCHAR(255) NOT NULL,
     DESCRIPTION VARCHAR(255),
     MAXIMUM     INTEGER,
     MINIMUM     INTEGER,
     NAME        VARCHAR(255) NOT NULL,
     PATTERN     VARCHAR(255),
     NULLABLE boolean NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX ATTRIBUTE_INDEX ON ATTRIBUTE(ID);

CREATE TABLE DOMAIN
  (
     ID          BIGINT NOT NULL AUTO_INCREMENT,
     DESCRIPTION VARCHAR(255),
     NAME        VARCHAR(255) NOT NULL,
     SELECTED    BIT NOT NULL,
     APP_ID  BIGINT NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX DOMAIN_INDEX ON DOMAIN(ID);

CREATE TABLE DOMAIN_ATTRIBUTES
  (
     DOMAIN_ENTITY_ID BIGINT NOT NULL,
     ATTRIBUTES_ID    BIGINT NOT NULL,
     PRIMARY KEY (DOMAIN_ENTITY_ID, ATTRIBUTES_ID)
  );
CREATE UNIQUE INDEX D_A_ATTRIBUTE_INDEX ON DOMAIN_ATTRIBUTES(ATTRIBUTES_ID);
CREATE INDEX D_A_DOMAIN_INDEX ON DOMAIN_ATTRIBUTES(DOMAIN_ENTITY_ID);


CREATE TABLE APP
  (
     ID            BIGINT NOT NULL AUTO_INCREMENT,
     DESCRIPTION   VARCHAR(255),
     PACKAGEPREFIX VARCHAR(100) NOT NULL,
     TARGETPATH    VARCHAR(100),
     TITLE         VARCHAR(100) NOT NULL,
     TEMPLATE_ID   BIGINT NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX APP_INDEX ON APP(ID);

CREATE TABLE APPTEMPLATE
  (
     ID                   BIGINT NOT NULL AUTO_INCREMENT,
     BRANCH               VARCHAR(100),
     CREDENTIALS_REQUIRED BIT NOT NULL,
     DESCRIPTION          VARCHAR(255),
     LOCATION             VARCHAR(100) NOT NULL,
     PREFIX               VARCHAR(100) NOT NULL,
     TITLE                VARCHAR(100) NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX TEMPLATE_INDEX ON APPTEMPLATE(ID);
CREATE INDEX APP_TEMPLATE_INDEX ON APP(TEMPLATE_ID);
CREATE INDEX DOMAIN_APP_INDEX ON DOMAIN(APP_ID);


CREATE TABLE CATEGORY
  (
     ID   BIGINT NOT NULL AUTO_INCREMENT,
     NAME VARCHAR(255) NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX CATEGORY_INDEX ON CATEGORY(ID);

CREATE TABLE TEMPLATEFILE
  (
     ID                 BIGINT NOT NULL AUTO_INCREMENT,
     CREATE_DOMAIN_DIR  BIT NOT NULL,
     FILE_NAME_SUFFIX   VARCHAR(100) NOT NULL,
     LOWER_CASE         BIT NOT NULL,
     TARGET_PATH        VARCHAR(255) NOT NULL,
     TEMPLATE_PATH      VARCHAR(255) NOT NULL,
     TEMPLATE_TYPE      VARCHAR(255) NOT NULL,
     FIRST_UPPER        BIT NOT NULL,
     CATEGORY_ID        BIGINT NOT NULL,
     APPTEMPLATE_ID BIGINT,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX TEMPLATEFILE_INDEX ON TEMPLATEFILE(ID);

CREATE TABLE TEMPLATEFILE_APP
  (
     TEMPLATEFILE_ID BIGINT NOT NULL,
     APP_ID      BIGINT NOT NULL,
     PRIMARY KEY (TEMPLATEFILE_ID, APP_ID)
  );

ALTER TABLE TEMPLATEFILE
  ADD CONSTRAINT FK_TEMPLATEFILE_CATEGORY FOREIGN KEY (CATEGORY_ID)
  REFERENCES CATEGORY (ID);

ALTER TABLE TEMPLATEFILE
  ADD CONSTRAINT FK_CODETEMPL_APPTEMPL FOREIGN KEY (APPTEMPLATE_ID)
  REFERENCES APPTEMPLATE (ID);

ALTER TABLE TEMPLATEFILE_APP
  ADD CONSTRAINT FK_TEMPLATEFILE_APP FOREIGN KEY (APP_ID) REFERENCES
  APP (ID);

ALTER TABLE TEMPLATEFILE_APP
  ADD CONSTRAINT FK_CODETEMPL_PROJ_CODETEMPL FOREIGN KEY (TEMPLATEFILE_ID)
  REFERENCES TEMPLATEFILE (ID);

ALTER TABLE DOMAIN
  ADD CONSTRAINT FK_DOMAIN_APP FOREIGN KEY (APP_ID) REFERENCES
  APP (ID);

ALTER TABLE DOMAIN_ATTRIBUTES
  ADD CONSTRAINT FK_DOMAIN_ATTR_ATTR FOREIGN KEY (ATTRIBUTES_ID)
  REFERENCES ATTRIBUTE (ID);

ALTER TABLE DOMAIN_ATTRIBUTES
  ADD CONSTRAINT FK_DOMAIN_ATTR_DOMAIN  FOREIGN KEY (DOMAIN_ENTITY_ID)
  REFERENCES DOMAIN (ID);

ALTER TABLE APP
  ADD CONSTRAINT FK_APP_APPTEMPL FOREIGN KEY (TEMPLATE_ID)
  REFERENCES APPTEMPLATE (ID);
