-- add enums as fieldtype
CREATE TABLE ENUM_DEF
(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ENUM_NAME VARCHAR(255) NOT NULL,
    ENUM_VALUE VARCHAR(500) NOT NULL,
    APP_ID INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE ATTRIBUTE ADD ENUM_DEF_ID INTEGER DEFAULT NULL;

ALTER TABLE ATTRIBUTE
ADD CONSTRAINT FK_ATTR_ENUM
FOREIGN KEY (ENUM_DEF_ID)
REFERENCES ENUM_DEF(ID);

CREATE INDEX ENUM_DEF_ATTR_INDEX ON ATTRIBUTE(ENUM_DEF_ID);

ALTER TABLE ENUM_DEF
ADD CONSTRAINT FK_ENUM_DEF_APP
FOREIGN KEY (APP_ID)
REFERENCES APP(ID);

CREATE INDEX ENUM_DEF_APP_INDEX ON ENUM_DEF(APP_ID);