apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ljprojectbuilder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ljprojectbuilder
    spec:
      containers:
      - name: ljprojectbuilder
        image: registry.gitlab.com/witchpou/lj-projectbuilder:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
