apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.fullname" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mariadb.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mariadb.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}
                  key: mariadb-password
          volumeMounts:
          - name: test-persistent-storage
            mountPath: /var/lib/mysql
          {{- if .Values.global.timezone }}
          - name: localtime
            mountPath: /etc/localtime
          - name: timezone
            mountPath: /etc/timezone
          {{- end }}
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}
          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - |
          #         password_aux="${MYSQL_ROOT_PASSWORD:-}"
          #         mysqladmin status -uroot -p$password_aux
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          #   timeoutSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 1
          # readinessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - |
          #         password_aux="${MYSQL_ROOT_PASSWORD:-}"
          #         mysqladmin status -uroot -p$password_aux
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 1
      volumes:
        - name: test-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "mariadb.fullname" . }}
        {{- if .Values.global.timezone }}
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          hostPath:
            path: /etc/timezone
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
