#------PVC mariadb files------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.db.size }}

#-----PVC timezones-------------------
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "mariadb.fullname" . }}-timezone
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 5Mbi

# #-----PVC timezones-------------------
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "mariadb.fullname" . }}-localtime
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 5Mbi