{{ if .Values.service.expose.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}-expose
  labels:
    app.kubernetes.io/name: {{ include "mariadb.fullname" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.service.expose.port }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "mariadb.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}