CREATE TABLE IF NOT EXISTS `APPTEMPLATE`
(
    `ID`      bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` varchar(255),
    `TEMPLATEFILES` varchar(255),
    `DESCRIPTION` varchar(255)
);
CREATE TABLE IF NOT EXISTS `TEMPLATEFILE`
(
    `ID`      bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESCRIPTION` varchar(255),
    `NAME` varchar(255)
);
CREATE TABLE IF NOT EXISTS `APP`
(
    `ID`      bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` varchar(255),
    `DESCRIPTION` varchar(255)
);
