version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx-init-letsencrypt.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./conf.d:/etc/nginx/conf.d
      - ./content:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  # Networks to be created to facilitate communication between containers
networks:
  backend: