version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'ljprojectbuilder'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ljprojectbuilder'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ljprojectbuilder'
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysql" ,"-h", "localhost", "-P", "3306", "-u", "root", "-e", "select 1", "ljprojectbuilder"]
      interval: 5s
      timeout: 60s
      retries: 30
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - /mnt/lj-mariadb/ljprojectbuilder:/var/lib/mysql
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      
  projectbuilder:
    image: starwitorg/ljprojectbuilder:v0.2.9
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ljprojectbuilder?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ljprojectbuilder
      SPRING_DATASOURCE_PASSWORD: ljprojectbuilder
      KEYCLOAK_AUTH-SERVER-URL: https://lj.starwit.de/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

 # Networks to be created to facilitate communication between containers
networks:
  backend:

