FROM openjdk:8-jre-alpine
# copy application JAR (with libraries inside)
COPY application/target/application-*.jar /application.jar
# specify default command
CMD ["/usr/bin/java", "-jar", "/application.jar"]
