CREATE TABLE APP
(
   ID integer NOT NULL AUTO_INCREMENT,
   DESCRIPTION varchar(255) DEFAULT NULL,
   PACKAGEPREFIX varchar(100) NOT NULL,
   TARGETPATH varchar(100) DEFAULT NULL,
   TITLE varchar(100) NOT NULL,
   TEMPLATE_ID integer NOT NULL,
   GROUPS varchar(1000) DEFAULT ',public,' NOT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE APPTEMPLATE
(
   ID integer NOT NULL AUTO_INCREMENT,
   BRANCH varchar(100) DEFAULT NULL,
   CREDENTIALS_REQUIRED BIT NOT NULL,
   DESCRIPTION varchar(255) DEFAULT NULL,
   LOCATION varchar(100) NOT NULL,
   PACKAGE varchar(100) NOT NULL,
   TEMPLATE_NAME varchar(100) NOT NULL,
   GROUPS varchar(1000) DEFAULT ',public,' NOT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE ATTRIBUTE
(
   ID integer NOT NULL AUTO_INCREMENT,
   TYPE varchar(255) NOT NULL,
   DESCRIPTION varchar(255) DEFAULT NULL,
   MAXIMUM integer DEFAULT NULL,
   MINIMUM integer DEFAULT NULL,
   NAME varchar(255) NOT NULL,
   PATTERN varchar(255) DEFAULT NULL,
   NULLABLE BIT NOT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE DIAGRAM_POSITION
(
   ID integer NOT NULL AUTO_INCREMENT,
   POSITION_X integer DEFAULT 0 NOT NULL,
   POSITION_Y integer DEFAULT 0 NOT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE DOMAIN
(
   ID integer NOT NULL AUTO_INCREMENT,
   DESCRIPTION varchar(255) DEFAULT NULL,
   NAME varchar(255) NOT NULL,
   APP_ID integer NOT NULL,
   POSITION_ID integer DEFAULT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE DOMAIN_ATTRIBUTES
(
   DOMAIN_ID integer NOT NULL,
   ATTRIBUTES_ID integer NOT NULL,
   PRIMARY KEY (DOMAIN_ID,ATTRIBUTES_ID)
)
;
CREATE TABLE DOMAIN_RELATIONSHIPS
(
   DOMAIN_ID integer NOT NULL,
   RELATIONSHIPS_ID integer NOT NULL,
   PRIMARY KEY (DOMAIN_ID,RELATIONSHIPS_ID)
)
;
CREATE TABLE RELATIONSHIP
(
   ID integer NOT NULL,
   TYPE varchar(255) NOT NULL AUTO_INCREMENT,
   OTHER_ENTITY_NAME varchar(255) NOT NULL,
   OTHER_ENTITY_RELATIONNAME varchar(255) NOT NULL,
   NAME varchar(255) NOT NULL,
   OWNER BIT NOT NULL,
   PRIMARY KEY (ID)
)
;
CREATE TABLE TEMPLATEFILE
(
   ID integer NOT NULL AUTO_INCREMENT,
   FILE_NAME_S varchar(100) NOT NULL,
   TARGET_PATH varchar(255) NOT NULL,
   TEMPLATE_PATH varchar(255) NOT NULL,
   APPTEMPLATE_ID integer DEFAULT NULL,
   CATEGORY varchar(255) NOT NULL,
   APPEND_TO_FILE BIT DEFAULT '0' NOT NULL,
   PRIMARY KEY (ID)
)
;
ALTER TABLE APP
ADD CONSTRAINT FK_APP_APPTEMPL
FOREIGN KEY (TEMPLATE_ID)
REFERENCES APPTEMPLATE(ID)
;
CREATE INDEX APP_TEMPLATE_INDEX ON APP(TEMPLATE_ID)
;
ALTER TABLE DOMAIN
ADD CONSTRAINT FK_DOMAIN_APP
FOREIGN KEY (APP_ID)
REFERENCES APP(ID)
;
ALTER TABLE DOMAIN
ADD CONSTRAINT FK_DOMAIN_POS
FOREIGN KEY (POSITION_ID)
REFERENCES DIAGRAM_POSITION(ID)
;
CREATE INDEX DOMAIN_APP_INDEX ON DOMAIN(APP_ID)
;
CREATE INDEX DOMAIN_POSTION_INDEX ON DOMAIN(POSITION_ID)
;
ALTER TABLE DOMAIN_ATTRIBUTES
ADD CONSTRAINT FK_DOMAIN_ATTR_ATTR
FOREIGN KEY (ATTRIBUTES_ID)
REFERENCES ATTRIBUTE(ID)
;
ALTER TABLE DOMAIN_ATTRIBUTES
ADD CONSTRAINT FK_DOMAIN_ATTR_DOMAIN
FOREIGN KEY (DOMAIN_ID)
REFERENCES DOMAIN(ID)
;
CREATE UNIQUE INDEX D_A_ATTRIBUTE_INDEX ON DOMAIN_ATTRIBUTES(ATTRIBUTES_ID)
;
CREATE INDEX D_A_DOMAIN_INDEX ON DOMAIN_ATTRIBUTES(DOMAIN_ID)
;
ALTER TABLE DOMAIN_RELATIONSHIPS
ADD CONSTRAINT FK_DOMAIN_REL_DOMAIN
FOREIGN KEY (DOMAIN_ID)
REFERENCES DOMAIN(ID)
;
ALTER TABLE DOMAIN_RELATIONSHIPS
ADD CONSTRAINT FK_DOMAIN_REL_REL
FOREIGN KEY (RELATIONSHIPS_ID)
REFERENCES RELATIONSHIP(ID)
;
CREATE INDEX D_R_ATTRIBUTE_INDEX ON DOMAIN_RELATIONSHIPS(DOMAIN_ID)
;
CREATE INDEX D_R_RELATIONSHIP_INDEX ON DOMAIN_RELATIONSHIPS(RELATIONSHIPS_ID)
;
ALTER TABLE TEMPLATEFILE
ADD CONSTRAINT FK_CODETEMPL_APPTEMPL
FOREIGN KEY (APPTEMPLATE_ID)
REFERENCES APPTEMPLATE(ID)
;
CREATE INDEX FK_CODETEMPL_APPTEMPL ON TEMPLATEFILE(APPTEMPLATE_ID)
;