{{- if .Values.oauth.enabled }}
{{- $clientid := required ".oauth.clientid not set" .Values.oauth.clientid }}
{{- $clientsecret := required ".oauth.clientsecret not set" .Values.oauth.clientsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth
  namespace: {{ .Release.Namespace }}
data:
  clientid: {{ .Values.oauth.clientid | b64enc }}
  clientsecret: {{ .Values.oauth.clientsecret | b64enc }}
{{- end }}
