{{- if .Values.mariadb.localstorage -}}
{{- $fullName := include "ljprojectbuilder.fullname" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/local-pv/ljpb-mariadb"
{{- end }}
