ALTER TABLE CODETEMPLATE ADD COLUMN PROJECTTEMPLATE_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE CODETEMPLATE
ADD CONSTRAINT FK_CT_PT
FOREIGN KEY (PROJECTTEMPLATE_ID)
REFERENCES PROJECTTEMPLATE(ID);

CREATE INDEX CT_PT_INDEX ON CODETEMPLATE(PROJECTTEMPLATE_ID);