apiVersion: v2
name: ljprojectbuilder-chart
description: A helm chart for projectbuilder

type: application

version: ${project.version}

appVersion: "${project.version}"

dependencies:
  - name: keycloak
    version: 18.1.1
    repository: https://codecentric.github.io/helm-charts
  - name: mariadb
    version: 11.0.13
    repository: https://charts.bitnami.com/bitnami
    
