global:
  keycloak:
    authServerUrl: https://app.projectbuilder.de/auth

replicaCount: 1

image:
  repository: starwitorg/ljprojectbuilder
  tag: "v0.3.3"
  pullPolicy: Always

imagePullSecrets:
  - name: github-docker-pull
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  
  hosts:
    - host: app.projectbuilder.de
  tls:
    - secretName: app.projectbuilder.de-tls
      hosts:
        - app.projectbuilder.de

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

mariadb:
  auth:
    rootPassword: root
    database: ljprojectbuilder
    username: ljprojectbuilder
    password: yourpassword

keycloak:
  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json  
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: yourpassword
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"      
  extraVolumeMounts: |
    - name: realm-json
      mountPath: "/realm/"
      readOnly: true    
  extraVolumes: |
    - name: realm-json
      configMap:
        name: {{ .Release.Name }}-realm-json    
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    rules:
      - host: app.projectbuilder.de
        paths:
          - path: /auth
            pathType: Prefix
    tls: 
      - secretName: app.projectbuilder.de-tls
        hosts:
        - app.projectbuilder.de
