CREATE TABLE ALLOWEDUSER
  (
     ID          BIGINT NOT NULL AUTO_INCREMENT,
     USERALIAS   VARCHAR(64) NOT NULL UNIQUE,
     USERROLE    VARCHAR(64) NOT NULL,
     PRIMARY KEY (ID)
  );
CREATE UNIQUE INDEX ALLOWEDUSER_INDEX ON ALLOWEDUSER(ID);

INSERT INTO `ALLOWEDUSER` (`USERALIAS`, `USERROLE`) VALUES
('ztarbug', 'PBUSER'),
('witchpou', 'PBUSER');