ALTER TABLE TEMPLATE ALTER COLUMN TEMPLATELOCATION RENAME TO LOCATION;
ALTER TABLE TEMPLATE ALTER COLUMN  TEMPLATEPREFIX RENAME TO PREFIX;
ALTER TABLE TEMPLATE ALTER COLUMN  TEMPLATE_TITLE RENAME TO TITLE;
ALTER TABLE TEMPLATE ADD BRANCH VARCHAR(100);